.github/workflows/lint.yml, .github/workflows/release.yml
=> GitHub Actions CI

charts/kamaji-etcd/Chart.yaml
Same fix as https://github.com/clastix/kamaji/pull/187
=> Fix installing on EKS

charts/kamaji-etcd/Chart.yaml, charts/kamaji-etcd/README.md, charts/kamaji-etcd/templates/_helpers.tpl
Fixing the lack of dynamic root client secret generation introduce with #7.
=> Non dynamic root client certs name

README.md, charts/kamaji-etcd/Chart.yaml, charts/kamaji-etcd/README.md, charts/kamaji-etcd/templates/_helpers.tpl, charts/kamaji-etcd/templates/etcd_cronjob_defrag.yaml, charts/kamaji-etcd/templates/etcd_datastore.yaml, charts/kamaji-etcd/values.yaml
=> Create datastore resource for Kamaji

charts/kamaji-etcd/Chart.yaml, charts/kamaji-etcd/README.md
=> upgrade etcd image

charts/kamaji-etcd/Chart.yaml, charts/kamaji-etcd/README.md, charts/kamaji-etcd/templates/etcd_datastore.yaml
=> defer datastore creation

charts/kamaji-etcd/templates/etcd_rbac.yaml, hack/.env, hack/certs/README.md, hack/certs/check.sh, hack/certs/renew.sh
=> etcd certs check and renew

charts/kamaji-etcd/README.md, charts/kamaji-etcd/values.yaml
=> Note on retention param

charts/kamaji-etcd/README.md, charts/kamaji-etcd/templates/etcd_sts.yaml, charts/kamaji-etcd/values.yaml
=> Use customAnnotations for the PVC

hack/datastore/README.md, hack/datastore/restore.sh
=> Move bash set parameters after debug check

charts/kamaji-etcd/templates/etcd_cronjob_backup.yaml, charts/kamaji-etcd/templates/etcd_cronjob_defrag.yaml, charts/kamaji-etcd/templates/etcd_job_postdelete.yaml, charts/kamaji-etcd/templates/etcd_job_postinstall_1.yaml, charts/kamaji-etcd/templates/etcd_job_postinstall_2.yaml, charts/kamaji-etcd/templates/etcd_job_s3retention.yaml
=> feat: support for jobs tolerations

doc/backup-and-restore.md
=> Datastore backup and restore short guide

charts/kamaji-etcd/README.md, charts/kamaji-etcd/templates/etcd_cronjob_backup.yaml, charts/kamaji-etcd/templates/etcd_cronjob_defrag.yaml, charts/kamaji-etcd/templates/etcd_job_preinstall_2.yaml, charts/kamaji-etcd/templates/etcd_sts.yaml, charts/kamaji-etcd/values.yaml
=> Add support for imagePullSecrets

charts/kamaji-etcd/README.md, charts/kamaji-etcd/templates/etcd_datastore.yaml, charts/kamaji-etcd/values.yaml
=> Config datastore name

charts/kamaji-etcd/templates/etcd_service_monitor.yaml
=> app.kubernetes.io/instance as monitor job selector

README.md, docs/monitoring.md, monitoring/grafana-dashboard.json
=> document how to monitor

charts/kamaji-etcd/README.md, charts/kamaji-etcd/templates/etcd_metrics_rbac.yaml, charts/kamaji-etcd/values.yaml
=> Service Account for scraping metrics

docs/performance-and-optimization.md
=> docs: improve documentation for performance test

charts/kamaji-etcd/templates/etcd_sts.yaml
=> set resources for etcd pods

charts/kamaji-etcd/README.md, charts/kamaji-etcd/templates/etcd_job_postdelete.yaml, charts/kamaji-etcd/templates/etcd_job_preinstall_1.yaml, charts/kamaji-etcd/templates/etcd_job_preinstall_2.yaml, charts/kamaji-etcd/values.yaml
=> use separated selector, affinity and tolerations for etcd and jobs

charts/kamaji-etcd/Chart.yaml, charts/kamaji-etcd/README.md, charts/kamaji-etcd/templates/etcd_job_preinstall_2.yaml, charts/kamaji-etcd/values.yaml
=> feat: use v3.5.16 for etcd

charts/kamaji-etcd/README.md, charts/kamaji-etcd/values.yaml
=>  feat: change default size of pvc

charts/kamaji-etcd/Chart.yaml, charts/kamaji-etcd/README.md
=> chore(helm): releasing v0.10.0

charts/kamaji-etcd/Chart.yaml, charts/kamaji-etcd/README.md
=> Update etcd version to 3.5.17

charts/kamaji-etcd/Chart.yaml
=> chore(helm): use same Kamaji chart icon

charts/kamaji-etcd/README.md, charts/kamaji-etcd/values.yaml
=> feat: enable liveness probe by default

charts/kamaji-etcd/README.md, charts/kamaji-etcd/values.yaml, docs/monitoring.md
=> fix: use safe default values for servicemonitor

LICENSE, charts/kamaji-etcd/LICENSE, scripts/backup.sh, scripts/certs-renew.sh, scripts/defrag.sh, scripts/etcd-client.sh, scripts/restore.sh, scripts/schedule.sh
=> chore: adding missing license identifiers
